### PR TITLE
Fixed build status shield

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Fixed an issue with the build status shield in README.md

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
This is fantastic, I was blissfully unaware of https://github.com/badges/shields/issues/8671

Would it be possible for you to do the same for some of the other repositories? It would be really useful if you could.

**Review by JimBobSquarePants — APPROVED** [review]

**Comment by MarkCiliaVincenti** [comment]
> This is fantastic, I was blissfully unaware of [badges/shields#8671](https://github.com/badges/shields/issues/8671)
> 
> Would it be possible for you to do the same for some of the other repositories? It would be really useful if you could.


Haha I could dedicate more time if you would consider accepting a PR making use of https://github.com/MarkCiliaVincenti/AsyncKeyedLock (available on NuGet as a library) as a replacement for the keyed locker you currently use :)

**Comment by JimBobSquarePants** [comment]
Aha!

We actually use a vastly different approach to the one described in the original SO question many moons ago. 

[The system is now lock free https://github.com/SixLabors/ImageSharp.Web/pull/124](https://github.com/SixLabors/ImageSharp.Web/pull/194)

This has been heavily tested and benchmarked.

**Comment by MarkCiliaVincenti** [comment]
> Aha!
> 
> We actually use a vastly different approach to the one described in the original SO question many moons ago.
> 
> [The system is now lock free https://github.com/SixLabors/ImageSharp.Web/pull/124](https://github.com/SixLabors/ImageSharp.Web/pull/194)
> 
> This has been heavily tested and benchmarked.

I will run some benchmarks against mine later :)

**Comment by MarkCiliaVincenti** [comment]
Hey @JimBobSquarePants what would you say is the % threshold in performance improvement you'd find acceptable to start using my library instead? I'm running benchmarks right now concurrently on a laptop in safe mode and on GitHub Actions and so far I see a noticeable improvement :)

**Comment by MarkCiliaVincenti** [comment]
Check it out @JimBobSquarePants 

https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/3741360562/jobs/6350865558

Depending on the conditions of the test, AsyncKeyLock from SharpLabor.ImageSharp.Web consumes 18% to 84% MORE memory, and the time it spends ranges between 1% and 64% more time.

Code for benchmarks at https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/

**Comment by MarkCiliaVincenti** [comment]
> > Aha!
> > We actually use a vastly different approach to the one described in the original SO question many moons ago.
> > [The system is now lock free https://github.com/SixLabors/ImageSharp.Web/pull/124](https://github.com/SixLabors/ImageSharp.Web/pull/194)
> > This has been heavily tested and benchmarked.
> 
> I will run some benchmarks against mine later :)

https://github.com/SixLabors/ImageSharp.Web/discussions/295

**Pull request merged**
