### PR TITLE
Js/faster cache hash

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Web/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Optimization to half the memory usage and speed up the performance of the hashing algorithm.

### CODE REVIEW

**Comment by sebastienros** [comment]
A reminder that I can run benchmarks for any branch, under load (lin/win and cloud/physical). I can give you the numbers for this one if you want. And I can also get you perfview traces if necessary.

**Comment by JimBobSquarePants** [comment]
@sebastienros I meant to tag you when I pushed this actually. Thanks! That would be really great.

**Comment by JimBobSquarePants** [comment]
@sebastienros Did you ever get the chance to benchmark this? I'd like to merge it in so we can release an updated version for consumption.

**Comment by sebastienros** [comment]
Should do it tomorrow

**Comment by JimBobSquarePants** [comment]
I'm gonna merge this, we can benchmark later. Super confident it's faster anyway.

**Pull request merged**
