### PR TITLE
Lock free Read/Write Identical Request Implementation

### PR DESCRIPTION
**Pull request by deanmarcussen**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Web/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Proposes replacing the `AsyncKeyLock` with an implementation based around `ConcurrentDictionary`.

Note: I have not removed the `AsyncKeyLock` code or related test code.

Test coverage from the Integration Tests.

### CODE REVIEW

**Review by JimBobSquarePants — APPROVED** [review]
Awesome, thanks!

**Comment by cristipufu** [comment]
@deanmarcussen @JimBobSquarePants can you guys please provide more details about this change? How is it better (pros/cons) vs the previous implementation with the AsyncLock?

**Comment by JimBobSquarePants** [comment]
It’s about 30x faster as I recall from the load test benchmarks

**Comment by sebastienros** [comment]
To be precise, under stress it went from 2K RPS to 60K RPS, which was the static file middleware raw perf.

**Comment by deanmarcussen** [comment]
Worth having a read of the full pr from @JimBobSquarePants https://github.com/SixLabors/ImageSharp.Web/pull/121 where the bottlenecks in the existing lock where identified and we tested the lock free approach

**Comment by cristipufu** [comment]
Thanks a lot guys!

**Pull request merged**
