### PR TITLE
Separate cache hash length and folder depth

### PR DESCRIPTION
**Pull request by ronaldbarendse**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Web/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
As discussed in https://github.com/SixLabors/ImageSharp.Web/discussions/210, this separates the cache hash length and (`PhysicalFileSystemCache` specific) cache folder depth. It also generates shorter cache file names by default by not repeating the characters that are already used in the nested folders.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
I've excluded the LRU cache from code coverage for now: I'm not sure why the coverage decreased, but it's completely missing dedicated tests to begin with.

**Comment by James-Jackson-South** [comment]
@ronaldbarendse Don't worry about the coverage and don't hide it. It's flaky as hell. I had a change recently observed when converting to png's to LFS pointers

**Comment by JimBobSquarePants** [comment]
@ronaldbarendse Don't worry about the coverage and don't hide it. It's flaky as hell. I had a change recently observed when converting to png's to LFS pointers

**Comment by ronaldbarendse** [comment]
Because I think adding a setting just for backwards compatibility isn't the best way forward, I thought about creating a sub-class called `LegacyV1PhysicalFileSystemCache` (similar naming as the `LegacyV1CacheKey`). This could then simply set the base class `useLegacyName` boolean using a protected constructor. But even this introduces code that needs to be cleaned up in the future, so I decided on using the fact that the cache depth and hash length are currently the same to revert back to creating the legacy/longer file paths: https://github.com/SixLabors/ImageSharp.Web/pull/213.

**Comment by James-Jackson-South** [comment]
I think closing this PR and opening another was a bit premature. Best leaving those kinds of decisions to the library owners.

**Comment by JimBobSquarePants** [comment]
I think closing this PR and opening another was a bit premature. Best leaving those kinds of decisions to the library owners.

**Comment by ronaldbarendse** [comment]
Fair enough, although I was pretty sure the other PR that doesn't require additional settings would be preferred 😇

**Pull request closed without merging**
